/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WS3DApp;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import ws3dproxy.CommandExecException;
import ws3dproxy.model.Creature;
import ws3dproxy.model.World;

/**
 *
 * @author stefanie
 */
public class App extends JFrame {
    private static World w;
    private static Creature creature;
    private static Modal modal;
    
//    @Override
//    public void keyTyped(KeyEvent e) {
//       //System.out.println("keyTyped - pressionado");
//    }
//    
//     @Override
//    public void keyReleased(KeyEvent e){
//        try{                      
//            if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
//                System.out.println("Direita");
//                creature.rotate(1);
//
//            } else if (e.getKeyCode() == KeyEvent.VK_LEFT) {
//                System.out.println("Esquerda");
//                creature.rotate(-1);
//
//            } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
//                System.out.println("BAIXO");
//                creature.move(-1.0, -1.0, 1.0);
//                
//            } else if (e.getKeyCode() == KeyEvent.VK_UP) {
//                System.out.println("CIMA");
//                creature.move(1.0, 1.0, 1.0);
//            }
//        } catch(CommandExecException ex){
//            System.out.println("Erro");
//        }       
//    }
//    
//    @Override
//    public void keyPressed(KeyEvent e) {
//       //System.out.println("keyPressed");
//    }
    
    
    public App() {
//      
//      SwingUtilities.invokeLater(() -> requestFocusInWindow());
        Modal modal = new Modal(null, true);
        modal.setVisible(true);
    }
    
    public static void main(String[] args) {
        try{
            VirtualWorld.CreateWorld();
            creature = VirtualCreature.CreateCreature();
            VirtualFood.CreateFood();
            VirtualJewel.CreateJewel();
            VirtualBrick.CreateBrick();
            VirtualWorld.OnTime(creature);
            
          //  App app = new App();
//            app.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
//            app.setVisible(true);
          javax.swing.SwingUtilities.invokeLater(() -> {
              App frame = new App();
              frame.setVisible(true);
            });
           
            
        } catch(Exception e){
            System.out.println("Erro");
        }
    }
}
